const carsRows = [
  { id: 'chevrolet-chevelle-malibu', name: 'Chevrolet Chevelle Malibu', mpg: 18, cylinders: 8, displacement: 307, horsepower: 130, weight: 3504, acceleration: 12, year: 1970, origin: 'USA' },
  { id: 'buick-skylark-320', name: 'Buick Skylark 320', mpg: 15, cylinders: 8, displacement: 350, horsepower: 165, weight: 3693, acceleration: 11.5, year: 1970, origin: 'USA' },
  { id: 'plymouth-satellite', name: 'Plymouth Satellite', mpg: 18, cylinders: 8, displacement: 318, horsepower: 150, weight: 3436, acceleration: 11, year: 1970, origin: 'USA' },
  { id: 'amc-rebel-sst', name: 'AMC Rebel SST', mpg: 16, cylinders: 8, displacement: 304, horsepower: 150, weight: 3433, acceleration: 12, year: 1970, origin: 'USA' },
  { id: 'ford-torino', name: 'Ford Torino', mpg: 17, cylinders: 8, displacement: 302, horsepower: 140, weight: 3449, acceleration: 10.5, year: 1970, origin: 'USA' },
  { id: 'ford-galaxie-500', name: 'Ford Galaxie 500', mpg: 15, cylinders: 8, displacement: 429, horsepower: 198, weight: 4341, acceleration: 10, year: 1970, origin: 'USA' },
  { id: 'chevrolet-impala', name: 'Chevrolet Impala', mpg: 14, cylinders: 8, displacement: 454, horsepower: 220, weight: 4354, acceleration: 9, year: 1970, origin: 'USA' },
  { id: 'plymouth-fury-iii', name: 'Plymouth Fury III', mpg: 14, cylinders: 8, displacement: 440, horsepower: 215, weight: 4312, acceleration: 8.5, year: 1970, origin: 'USA' },
  { id: 'pontiac-catalina', name: 'Pontiac Catalina', mpg: 14, cylinders: 8, displacement: 455, horsepower: 225, weight: 4425, acceleration: 10, year: 1970, origin: 'USA' },
  { id: 'toyota-corona-mark-ii', name: 'Toyota Corona Mark II', mpg: 24, cylinders: 4, displacement: 113, horsepower: 95, weight: 2372, acceleration: 15, year: 1970, origin: 'Japan' },
  { id: 'plymouth-duster', name: 'Plymouth Duster', mpg: 22, cylinders: 6, displacement: 198, horsepower: 95, weight: 2833, acceleration: 15.5, year: 1970, origin: 'USA' },
  { id: 'amc-hornet', name: 'AMC Hornet', mpg: 18, cylinders: 6, displacement: 199, horsepower: 97, weight: 2774, acceleration: 15.5, year: 1970, origin: 'USA' },
  { id: 'ford-maverick', name: 'Ford Maverick', mpg: 21, cylinders: 6, displacement: 200, horsepower: 85, weight: 2587, acceleration: 16, year: 1970, origin: 'USA' },
  { id: 'datsun-pl510', name: 'Datsun PL510', mpg: 27, cylinders: 4, displacement: 97, horsepower: 88, weight: 2130, acceleration: 14.5, year: 1970, origin: 'Japan' },
  { id: 'volkswagen-1131-deluxe-sedan', name: 'Volkswagen 1131 Deluxe Sedan', mpg: 26, cylinders: 4, displacement: 97, horsepower: 46, weight: 1835, acceleration: 20.5, year: 1970, origin: 'Europe' },
  { id: 'peugeot-504', name: 'Peugeot 504', mpg: 25, cylinders: 4, displacement: 110, horsepower: 87, weight: 2672, acceleration: 17.5, year: 1970, origin: 'Europe' },
  { id: 'audi-100-ls', name: 'Audi 100 LS', mpg: 24, cylinders: 4, displacement: 107, horsepower: 90, weight: 2430, acceleration: 14.5, year: 1970, origin: 'Europe' },
  { id: 'saab-99e', name: 'Saab 99E', mpg: 25, cylinders: 4, displacement: 104, horsepower: 95, weight: 2375, acceleration: 17.5, year: 1970, origin: 'Europe' },
  { id: 'bmw-2002', name: 'BMW 2002', mpg: 26, cylinders: 4, displacement: 121, horsepower: 113, weight: 2234, acceleration: 12.5, year: 1970, origin: 'Europe' },
  { id: 'amc-gremlin', name: 'AMC Gremlin', mpg: 21, cylinders: 6, displacement: 199, horsepower: 90, weight: 2648, acceleration: 15, year: 1970, origin: 'USA' },
  { id: 'ford-pinto', name: 'Ford Pinto', mpg: 25, cylinders: 4, displacement: 98, horsepower: 90, weight: 2265, acceleration: 15.5, year: 1971, origin: 'USA' },
  { id: 'toyota-corolla-1200', name: 'Toyota Corolla 1200', mpg: 31, cylinders: 4, displacement: 71, horsepower: 65, weight: 1773, acceleration: 19, year: 1971, origin: 'Japan' },
  { id: 'datsun-1200', name: 'Datsun 1200', mpg: 35, cylinders: 4, displacement: 72, horsepower: 69, weight: 1613, acceleration: 18, year: 1971, origin: 'Japan' },
  { id: 'volkswagen-super-beetle', name: 'Volkswagen Super Beetle', mpg: 26, cylinders: 4, displacement: 97, horsepower: 48, weight: 1978, acceleration: 20, year: 1971, origin: 'Europe' },
  { id: 'chevrolet-vega-2300', name: 'Chevrolet Vega 2300', mpg: 28, cylinders: 4, displacement: 140, horsepower: 90, weight: 2264, acceleration: 15.5, year: 1971, origin: 'USA' },
  { id: 'ford-gran-torino', name: 'Ford Gran Torino', mpg: 14, cylinders: 8, displacement: 351, horsepower: 153, weight: 4154, acceleration: 13.5, year: 1972, origin: 'USA' },
  { id: 'amc-matador', name: 'AMC Matador', mpg: 15, cylinders: 8, displacement: 304, horsepower: 150, weight: 3892, acceleration: 12.5, year: 1972, origin: 'USA' },
  { id: 'plymouth-fury-iii-72', name: 'Plymouth Fury III 72', mpg: 13, cylinders: 8, displacement: 318, horsepower: 150, weight: 4135, acceleration: 13.5, year: 1972, origin: 'USA' },
  { id: 'volvo-145e-sw', name: 'Volvo 145e SW', mpg: 18, cylinders: 4, displacement: 121, horsepower: 112, weight: 2933, acceleration: 14.5, year: 1972, origin: 'Europe' },
  { id: 'toyota-mark-ii', name: 'Toyota Mark II', mpg: 23, cylinders: 4, displacement: 97, horsepower: 88, weight: 2279, acceleration: 19, year: 1972, origin: 'Japan' },
  { id: 'mercedes-benz-280s', name: 'Mercedes-Benz 280S', mpg: 16.5, cylinders: 6, displacement: 168, horsepower: 120, weight: 3820, acceleration: 16.7, year: 1972, origin: 'Europe' },
  { id: 'fiat-124b', name: 'Fiat 124B', mpg: 30, cylinders: 4, displacement: 88, horsepower: 76, weight: 2065, acceleration: 14.5, year: 1972, origin: 'Europe' },
]

export const WORKSPACE_CASES = [
  {
    id: 'cars-horsepower',
    title: 'Cars Horsepower Study',
    summary: 'Inspect how horsepower, efficiency, weight, and origin distribute across a mid-century car dataset.',
    topology: 'grid-overview',
    dataset: {
      name: 'Cars horsepower subset',
      rows: carsRows.length,
      fields: 8,
      coverage: '1970-1972 · USA / Europe / Japan',
      rowsData: carsRows,
      horsepowerDomain: [40, 230],
      origins: ['USA', 'Europe', 'Japan'],
      cylinders: [4, 6, 8],
      years: [1970, 1971, 1972],
    },
    widgets: [
      {
        id: 'w_scatter_cars',
        title: 'Horsepower vs MPG',
        subtitle: 'Brush a region directly in the plot',
        type: 'scatter-vega',
        widgetKind: 'scatter',
        provider: 'vega-lite',
        role: 'overview',
        insight: 'High-horsepower cars cluster with lower MPG, while Japanese imports concentrate in the light, efficient region.',
        metrics: ['scatter', 'origin color'],
        encodings: ['x: horsepower', 'y: mpg', 'color: origin', 'size: weight'],
      },
      {
        id: 'w_bar_origin',
        title: 'Average Horsepower by Origin',
        subtitle: 'Click a bar to filter by origin',
        type: 'bar-echarts',
        widgetKind: 'bar',
        provider: 'echarts',
        role: 'comparison',
        insight: 'USA cars carry the highest average horsepower; Europe sits in the middle and Japan trends lower.',
        metrics: ['mean hp', '3 origins'],
        encodings: ['x: origin', 'y: avg horsepower'],
      },
      {
        id: 'w_line_year',
        title: 'MPG Trend by Model Year',
        subtitle: 'Click a point to filter by year',
        type: 'line-vega',
        widgetKind: 'line',
        provider: 'vega-lite',
        role: 'context',
        insight: 'The smaller imported cars remain more fuel-efficient across these early model years.',
        metrics: ['mean mpg', '3 years'],
        encodings: ['x: year', 'y: avg mpg', 'color: origin'],
      },
      {
        id: 'w_heatmap_origin_cyl',
        title: 'Origin x Cylinders',
        subtitle: 'Click a cell to filter origin and cylinders',
        type: 'heatmap-vega',
        widgetKind: 'heatmap',
        provider: 'vega-lite',
        role: 'comparison',
        insight: 'Large-cylinder cars remain concentrated in the USA, while imports cluster in 4-cylinder configurations.',
        metrics: ['avg hp', 'origin x cylinders'],
        encodings: ['x: cylinders', 'y: origin', 'color: avg horsepower'],
      },
      {
        id: 'w_parallel_cars',
        title: 'Parallel Coordinates',
        subtitle: 'Click a polyline to focus one car',
        type: 'parallel-custom',
        widgetKind: 'parallelCoordinates',
        provider: 'd3',
        role: 'detail',
        insight: 'Parallel coordinates expose how horsepower, MPG, weight, and acceleration co-vary across the filtered cars.',
        metrics: ['4 dimensions', 'car focus'],
        encodings: ['axes: horsepower, mpg, weight, acceleration', 'line: car'],
      },
      {
        id: 'w_sankey_cars',
        title: 'Origin to Cylinders to Year',
        subtitle: 'Click a node to filter the flow',
        type: 'sankey-custom',
        widgetKind: 'sankey',
        provider: 'd3',
        role: 'detail',
        insight: 'The flow view compresses how cars move from region to engine class and then into model year.',
        metrics: ['origin', 'cylinders', 'year'],
        encodings: ['origin -> cylinders -> year'],
      },
    ],
    findings: [
      {
        title: 'Horsepower and fuel economy diverge sharply above 140 hp',
        note: 'The primary scatter separates heavy US cars from lighter imports once horsepower moves into the upper tail.',
        widgetId: 'w_scatter_cars',
        confidence: 'working',
        provenance: 'manual',
      },
    ],
    trace: [],
    agentChat: [],
    replaySteps: [
      { id: 'r1', title: 'Baseline workspace', detail: 'Six linked views expose the same car subset from complementary encodings.' },
      { id: 'r2', title: 'Filter pass', detail: 'Origin, year, and cylinder filters reshape all views in a coordinated way.' },
    ],
    branches: [
      { id: 'b1', label: 'Main analysis path', origin: 'workspace load', status: 'active' },
    ],
    log: [
      { id: 'l1', type: 'observe', text: 'Cars dataset seeded into a six-widget coordinated analysis surface.' },
      { id: 'l2', type: 'filter', text: 'Shared filters drive all views rather than isolated chart-local state.' },
    ],
  },
]
