function clone(value) {
  return value == null ? value : JSON.parse(JSON.stringify(value))
}

export const WIDGET_VERIFICATION_EFFECT_TYPES = [
  'selection',
  'filter',
  'sort',
  'aggregate',
  'drillDown',
  'reencode',
  'annotate',
  'addRemove',
  'navigate',
  'zoom',
  'highlight',
  'focus',
  'encoding',
  'linkedPropagation',
]

export const WIDGET_VERIFICATION_CONTRACTS = {
  bar: {
    preferredReadMethod: 'readVerificationState',
    preferredObservationFields: [
      'verification.checks.selectionApplied',
      'verification.checks.filterApplied',
      'verification.checks.sortApplied',
      'verification.checks.reencodeApplied',
      'verification.checks.addRemoveApplied',
      'verification.checks.highlightApplied',
      'verification.encodings.channels',
      'verification.view.addRemove',
      'verification.view.reencode',
      'verification.view.sort',
      'verification.view.highlight',
      'verification.transforms.kinds',
    ],
    supportedEffectTypes: ['selection', 'filter', 'sort', 'reencode', 'addRemove', 'highlight', 'encoding', 'linkedPropagation'],
    effectChecks: {
      selection: ['checks.selectionApplied', 'selections.count', 'selections.activeSummary'],
      filter: ['checks.filterApplied', 'data.rowCount', 'data.visibleCount', 'transforms.kinds'],
      sort: ['checks.sortApplied', 'view.sort'],
      reencode: ['checks.reencodeApplied', 'view.reencode', 'encodings.channels'],
      addRemove: ['checks.addRemoveApplied', 'view.addRemove', 'data.visibleCount'],
      highlight: ['checks.highlightApplied', 'view.highlight', 'feedback.highlightKeyCount', 'feedback.sharedSelectionSourceWidgetId'],
      encoding: ['checks.encodingReadable', 'encodings.channels', 'encodings.fieldsByChannel'],
      linkedPropagation: ['checks.linkedPropagationApplied', 'feedback.linkedSourceRefCount', 'feedback.sharedSelectionSourceWidgetId'],
    },
  },
  line: {
    preferredReadMethod: 'readVerificationState',
    preferredObservationFields: [
      'verification.checks.selectionApplied',
      'verification.checks.filterApplied',
      'verification.checks.aggregateApplied',
      'verification.checks.drillDownApplied',
      'verification.checks.focusApplied',
      'verification.checks.annotateApplied',
      'verification.checks.navigateApplied',
      'verification.checks.zoomApplied',
      'verification.checks.highlightApplied',
      'verification.encodings.channels',
      'verification.view.aggregate',
      'verification.view.drillDown',
      'verification.view.focusKeys',
      'verification.view.annotate',
      'verification.view.navigate',
      'verification.view.highlight',
      'verification.transforms.kinds',
    ],
    supportedEffectTypes: ['selection', 'filter', 'aggregate', 'drillDown', 'focus', 'annotate', 'navigate', 'zoom', 'highlight', 'encoding', 'linkedPropagation'],
    effectChecks: {
      selection: ['checks.selectionApplied', 'selections.count', 'selections.activeSummary'],
      filter: ['checks.filterApplied', 'data.rowCount', 'data.visibleCount', 'transforms.kinds'],
      aggregate: ['checks.aggregateApplied', 'view.aggregate', 'encodings.aggregateChannels'],
      drillDown: ['checks.drillDownApplied', 'view.drillDown', 'transforms.kinds'],
      focus: ['checks.focusApplied', 'view.focusKeys'],
      annotate: ['checks.annotateApplied', 'view.annotate'],
      navigate: ['checks.navigateApplied', 'view.navigate'],
      zoom: ['checks.zoomApplied', 'view.xDomain', 'view.zoom'],
      highlight: ['checks.highlightApplied', 'view.highlight', 'feedback.highlightKeyCount', 'feedback.sharedSelectionSourceWidgetId'],
      encoding: ['checks.encodingReadable', 'encodings.channels', 'encodings.fieldsByChannel'],
      linkedPropagation: ['checks.linkedPropagationApplied', 'feedback.linkedSourceRefCount', 'feedback.sharedSelectionSourceWidgetId'],
    },
  },
  scatter: {
    preferredReadMethod: 'readVerificationState',
    preferredObservationFields: [
      'verification.checks.selectionApplied',
      'verification.checks.filterApplied',
      'verification.checks.annotateApplied',
      'verification.checks.zoomApplied',
      'verification.encodings.channels',
      'verification.view.annotate',
      'verification.selections.activeKinds',
    ],
    supportedEffectTypes: ['selection', 'filter', 'zoom', 'highlight', 'annotate', 'encoding', 'linkedPropagation'],
    effectChecks: {
      selection: ['checks.selectionApplied', 'selections.count', 'selections.activeKinds', 'selections.activeSummary'],
      filter: ['checks.filterApplied', 'data.rowCount', 'data.visibleCount', 'transforms.kinds'],
      zoom: ['checks.zoomApplied', 'view.xDomain', 'view.yDomain', 'view.zoom'],
      annotate: ['checks.annotateApplied', 'view.annotate'],
      highlight: ['checks.highlightApplied', 'feedback.highlightKeyCount', 'feedback.sharedSelectionSourceWidgetId'],
      encoding: ['checks.encodingReadable', 'encodings.channels', 'encodings.fieldsByChannel'],
      linkedPropagation: ['checks.linkedPropagationApplied', 'feedback.linkedSourceRefCount', 'feedback.sharedSelectionSourceWidgetId'],
    },
  },
  heatmap: {
    preferredReadMethod: 'readVerificationState',
    preferredObservationFields: [
      'verification.checks.selectionApplied',
      'verification.checks.filterApplied',
      'verification.checks.aggregateApplied',
      'verification.checks.drillDownApplied',
      'verification.checks.reencodeApplied',
      'verification.checks.annotateApplied',
      'verification.checks.navigateApplied',
      'verification.checks.highlightApplied',
      'verification.encodings.channels',
      'verification.view.aggregate',
      'verification.view.drillDown',
      'verification.view.reencode',
      'verification.view.annotate',
      'verification.view.navigate',
      'verification.view.highlight',
      'verification.selections.activeKinds',
    ],
    supportedEffectTypes: ['selection', 'filter', 'aggregate', 'drillDown', 'reencode', 'annotate', 'navigate', 'highlight', 'encoding', 'linkedPropagation'],
    effectChecks: {
      selection: ['checks.selectionApplied', 'selections.count', 'selections.activeKinds', 'selections.activeSummary'],
      filter: ['checks.filterApplied', 'data.rowCount', 'data.visibleCount', 'transforms.kinds'],
      aggregate: ['checks.aggregateApplied', 'view.aggregate', 'view.sort'],
      drillDown: ['checks.drillDownApplied', 'view.drillDown', 'transforms.kinds'],
      reencode: ['checks.reencodeApplied', 'view.reencode', 'encodings.channels'],
      annotate: ['checks.annotateApplied', 'view.annotate'],
      navigate: ['checks.navigateApplied', 'view.navigate'],
      highlight: ['checks.highlightApplied', 'view.highlight', 'feedback.highlightKeyCount', 'feedback.sharedSelectionSourceWidgetId'],
      encoding: ['checks.encodingReadable', 'encodings.channels', 'encodings.fieldsByChannel'],
      linkedPropagation: ['checks.linkedPropagationApplied', 'feedback.linkedSourceRefCount', 'feedback.sharedSelectionSourceWidgetId'],
    },
  },
  parallelCoordinates: {
    preferredReadMethod: 'readVerificationState',
    preferredObservationFields: [
      'verification.checks.selectionApplied',
      'verification.checks.filterApplied',
      'verification.checks.highlightApplied',
      'verification.checks.reencodeApplied',
      'verification.checks.focusApplied',
      'verification.selections.activeKinds',
      'verification.view.highlight',
      'verification.view.reencode',
      'verification.transforms.kinds',
    ],
    supportedEffectTypes: ['selection', 'filter', 'highlight', 'focus', 'reencode', 'encoding', 'linkedPropagation'],
    effectChecks: {
      selection: ['checks.selectionApplied', 'selections.count', 'selections.activeKinds', 'selections.activeSummary'],
      filter: ['checks.filterApplied', 'data.rowCount', 'data.visibleCount', 'transforms.kinds'],
      highlight: ['checks.highlightApplied', 'view.highlight', 'feedback.highlightKeyCount', 'feedback.sharedSelectionSourceWidgetId'],
      focus: ['checks.focusApplied', 'view.focusKeys'],
      reencode: ['checks.reencodeApplied', 'view.reencode', 'encodings.channels'],
      encoding: ['checks.encodingReadable', 'encodings.channels', 'encodings.fieldsByChannel'],
      linkedPropagation: ['checks.linkedPropagationApplied', 'feedback.linkedSourceRefCount', 'feedback.sharedSelectionSourceWidgetId'],
    },
  },
  sankey: {
    preferredReadMethod: 'readVerificationState',
    preferredObservationFields: [
      'verification.checks.selectionApplied',
      'verification.checks.filterApplied',
      'verification.checks.aggregateApplied',
      'verification.checks.reencodeApplied',
      'verification.checks.navigateApplied',
      'verification.checks.highlightApplied',
      'verification.checks.focusApplied',
      'verification.view.aggregate',
      'verification.view.reencode',
      'verification.view.navigate',
      'verification.view.highlight',
      'verification.transforms.kinds',
    ],
    supportedEffectTypes: ['selection', 'filter', 'aggregate', 'reencode', 'navigate', 'highlight', 'focus', 'encoding', 'linkedPropagation'],
    effectChecks: {
      selection: ['checks.selectionApplied', 'selections.count', 'selections.activeKinds', 'selections.activeSummary'],
      filter: ['checks.filterApplied', 'data.rowCount', 'data.visibleCount', 'transforms.kinds'],
      aggregate: ['checks.aggregateApplied', 'view.aggregate'],
      reencode: ['checks.reencodeApplied', 'view.reencode', 'encodings.channels'],
      navigate: ['checks.navigateApplied', 'view.navigate'],
      highlight: ['checks.highlightApplied', 'view.highlight', 'feedback.highlightKeyCount', 'feedback.sharedSelectionSourceWidgetId'],
      focus: ['checks.focusApplied', 'view.focusKeys'],
      encoding: ['checks.encodingReadable', 'encodings.channels', 'encodings.fieldsByChannel'],
      linkedPropagation: ['checks.linkedPropagationApplied', 'feedback.linkedSourceRefCount', 'feedback.sharedSelectionSourceWidgetId'],
    },
  },
}

export function describeWidgetVerificationContract(kind) {
  return clone(WIDGET_VERIFICATION_CONTRACTS[kind] || null)
}
